### ISSUE TITLE
Cannot install this package on Laravel 7.x

### ISSUE THREAD

**Issue by kresnasatya** [matt-allan/passport-socialite#4]
Hi @matt-allan, I would like to install this package in Laravel 7.x but it doesn't support. Here's the error message

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for matt-allan/passport-socialite ^0.2.0 -> satisfiable by matt-allan/passport-socialite[0.2.0].
    - Conclusion: remove laravel/framework v7.2.0
    - Conclusion: don't install laravel/framework v7.2.0
```

**Comment by matt-allan** [comment]
Hello,

Thanks for opening the issue. Feel free to open a PR. Otherwise I will hopefully get to it in the next week.

Should just need to add `|^7.0` to the end of this line: https://github.com/matt-allan/passport-socialite/blob/5b9688588a92d52abde2f5e604f27a553fd7b153/composer.json#L26

**Comment by kresnasatya** [comment]
Hi @matt-allan, I will try to create a PR. Thank you.

**Comment by matt-allan** [comment]
Thanks! Leaving this open until I create a new tag.

**Comment by matt-allan** [comment]
Tagged! Let me know if you run into anymore issues.
